---
  - hosts: all
    become: yes
    tasks:
      - name: install packages
        pacman:
          name:
          - curl
          - git
          - htop
          - nano
          - neovim
          - wget
          - xdg-user-dirs
      - name: install gui packages
        pacman:
          name:
           - ark
           - firefox
           - kwrite
           - okular
      - name: create sddm config directory
        file:
          path: /etc/sddm.conf.d
          state: directory
          owner: root
          group: root
          mode: '0755'
      - name: copy sddm autologin config
        template:
            src: etc/sddm.conf.d/kde_settings.conf.j2
            dest: /etc/sddm.conf.d/kde_settings.conf
            owner: root
            group: root
            mode: '0644'
      - name: reboot to complete setup
        reboot:
